### VALUES YOU SHOULD CHANGE ###
# GENERAL SITE SETTINGS
title: Dogcatquokka
description: Dogcatquokka's Portfolio Website
baseurl: ""

# LANDING PAGE
username: Dogcatquokka
typing_text: This is my portfolio website
email: dlwodn9910@naver.com
github_username: Dogcatquokka
blog_username: flfns333

# ABOUT ME SECTION
show_aboutme_card: true
about_me_title: About Me
about_me_description: "I am a passionate individual interested in technology and eager to learn more about programming and development."

# SKILLS SECTION
show_skills_card: true
skills_title: Skills

# TIMELINE SECTION
show_timeline_card: true
timeline_title: Education & Experience
cv_download_link: https://example.com/

# PROJECTS SECTION
show_projects_card: true
show_projects: true
projects_title: Projects
show_os_projects: false
os_projects_title: Open Source Projects

show_certificates_card: true
show_certificates: true
certificates_title: Certificates

# CONTACT SECTION
show_contact_card: true
contact_title: Contact
contact_description: The way to reach me is always open. Communicate and share knowledge~!🙌

# GITHUB-METADATA
repository: Dogcatquokka/Dogcatquokka.github.io
projects:
  sort_by: pushed
  exclude:
    archived: true
    forks: true

# GOOGLE-ANALYTICS
google-analytics:
  id: "G-J0Y003ME19"

### END OF VALUES YOU SHOULD CHANGE ###

plugins:
  - "jekyll-github-metadata"

exclude:
  - "_assets"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpfile.js"
  - "node_modules"
  - "package.json"

Params:
  mod_icons:
    enableAutoTitle: true
    enableStats: false
    defaultLoader: svg-use
    defaultLoaderShortcode: svg-inline
    iconBaseClass: icon

module:
  hugoVersion:
    extended: true
    min: "0.80.0"  
    max: "1.00.0"
  imports:
    - path: "github.com/FortAwesome/Font-Awesome"
      mounts:
        - source: "svgs/"
          target: "assets/mod-icons/fa/svg/"
        - source: "metadata/"
          target: "assets/mod-icons/fa/meta/"
